# Generated by Django 4.0.5 on 2022-07-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_total_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='total_duration',
        ),
    ]
